CREATE TABLE [Customers] (
  [ID] AUTOINCREMENT CONSTRAINT [PrimaryKey] PRIMARY KEY UNIQUE NOT NULL,
  [Nombre] VARCHAR (50),
  [Apellido] VARCHAR (50),
  [NombreCompleto] VARCHAR (243),
  [RazonONombreCompleto] VARCHAR (243),
  [Correo] VARCHAR (50),
  [TelefonoFijo] VARCHAR (25),
  [Celular] VARCHAR (25),
  [Direccion] VARCHAR (255),
  [Ciudad] VARCHAR (50),
  [Provincia] VARCHAR (50),
  [Pais] VARCHAR (50),
  [Notas] LONGTEXT ,
  [Adjuntos] VARCHAR ,
  [TipoDeDocumento] VARCHAR (255),
  [FechaDeNacimiento] DATETIME ,
  [Condicion] VARCHAR (255),
  [Genero] VARCHAR (255),
  [RazonSocial] VARCHAR (255),
  [RUC] VARCHAR (255),
  [DV] VARCHAR (255),
  [TipoDeCliente] VARCHAR (255),
  [EsDoctor] BIT ,
  [NumeroDeIdentificacion] VARCHAR (255),
  [Corregimiento] VARCHAR (255),
  [UpdatedAt] DATETIME ,
  [UpdatedBy] VARCHAR (255),
  [CreatedAt] DATETIME ,
  [Secretaria] VARCHAR (255),
  [TelefonoSecretaria] VARCHAR (255),
  [OtroTelefono] VARCHAR (255),
  [OtroTelefonoDescripcion] VARCHAR (255),
  [Especialidad] LONG ,
  [EsActivo] BIT ,
  [LugarDeReferencia1] VARCHAR (255),
  [LugarDeReferencia2] VARCHAR (255),
  [LugarDeReferencia3] VARCHAR (255),
  [LugarDeTrabajo1] VARCHAR (255),
  [LugarDeTrabajo2] VARCHAR (255),
  [RegaliaCompra] CURRENCY ,
  [RegaliaAlquiler] CURRENCY ,
  [Status] VARCHAR (255),
  [FollowupDate] DATETIME 
)
