CREATE TABLE [Visits] (
  [Id] AUTOINCREMENT CONSTRAINT [PrimaryKey] PRIMARY KEY UNIQUE NOT NULL,
  [DoctorId] LONG ,
  [EmpleadoId] LONG ,
  [Estatus] VARCHAR (255),
  [FechaProgramada] DATETIME ,
  [HoraProgramada] DATETIME ,
  [Observacion] VARCHAR (255),
  [FechaDeFollowup] DATETIME ,
  [DocumentosAdjuntos] VARCHAR ,
  [Telefono] VARCHAR (255),
  [Direccion] VARCHAR (255),
  [Ciudad] VARCHAR (50),
  [Provincia] VARCHAR (50),
  [Pais] VARCHAR (50),
  [Corregimiento] VARCHAR (255),
  [Secretaria] VARCHAR (255),
  [TelefonoDelaSecretaria] VARCHAR (255),
  [Notas] LONGTEXT ,
  [InstalacionDeSalud] VARCHAR (255),
  [Sede] VARCHAR (255),
  [Piso] VARCHAR (255),
  [NumeroDeConsultorio] VARCHAR (255),
  [UpdatedAt] DATETIME ,
  [UpdatedBy] VARCHAR (255)
)
